version: "3"
services:
  postgres:
      container_name: postgres_container
      image: hellosummer1705/postgres:prod
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: slsZ1XmB
        PGDATA: /data/postgres
      volumes:
        - postgres:/data/postgres
      ports:
        - "5432:5432"
      networks:
        - student-manage-network
      restart: unless-stopped


  student-manage-be:
    platform: linux/amd64
    image: hellosummer1705/student-manage-be:v1.0.0
    container_name: student-manage-be
    restart: unless-stopped
    build: .
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: postgres
      DATABASE_NAME: student-manage
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: slsZ1XmB
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - student-manage-network

networks:
  student-manage-network:
    external: true

volumes:
    postgres: